# AUTOGENERATED, DON'T CHANGE THIS FILE!


if (NOT USERVER_CHECK_PACKAGE_VERSIONS)
  unset(PostgreSQLInternal_FIND_VERSION)
endif()

if (TARGET PostgreSQLInternal)
  if (NOT PostgreSQLInternal_FIND_VERSION)
      set(PostgreSQLInternal_FOUND ON)
      return()
  endif()

  if (PostgreSQLInternal_VERSION)
      if (PostgreSQLInternal_FIND_VERSION VERSION_LESS_EQUAL PostgreSQLInternal_VERSION)
          set(PostgreSQLInternal_FOUND ON)
          return()
      else()
          message(FATAL_ERROR
              "Already using version ${PostgreSQLInternal_VERSION} "
              "of PostgreSQLInternal when version ${PostgreSQLInternal_FIND_VERSION} "
              "was requested."
          )
      endif()
  endif()
endif()

set(FULL_ERROR_MESSAGE "Could not find `PostgreSQLInternal` package.\n\tDebian: sudo apt update && sudo apt install libpq-dev postgresql-server-dev-12\n\tMacOS: brew install postgresql@14\n\tFedora: sudo dnf install postgresql-server-devel postgresql-static\n\tFreeBSD: pkg install postgresql15-server\\n")


include(FindPackageHandleStandardArgs)

find_library(PostgreSQLInternal_LIBRARIES_libpq_a
  NAMES libpq.a
  PATHS ${USERVER_PG_LIBRARY_DIR} /usr/local/lib
)
list(APPEND PostgreSQLInternal_LIBRARIES ${PostgreSQLInternal_LIBRARIES_libpq_a})
find_library(PostgreSQLInternal_LIBRARIES_libpgcommon_a
  NAMES libpgcommon.a
  PATHS /usr/lib/postgresql/12/lib /usr/lib/postgresql/13/lib /usr/lib/postgresql/14/lib /usr/lib/postgresql/15/lib ${USERVER_PG_PKGLIB_DIR} ${USERVER_PG_LIBRARY_DIR}
)
list(APPEND PostgreSQLInternal_LIBRARIES ${PostgreSQLInternal_LIBRARIES_libpgcommon_a})
find_library(PostgreSQLInternal_LIBRARIES_libpgport_a
  NAMES libpgport.a
  PATHS /usr/lib/postgresql/12/lib /usr/lib/postgresql/13/lib /usr/lib/postgresql/14/lib /usr/lib/postgresql/15/lib ${USERVER_PG_PKGLIB_DIR} ${USERVER_PG_LIBRARY_DIR}
)
list(APPEND PostgreSQLInternal_LIBRARIES ${PostgreSQLInternal_LIBRARIES_libpgport_a})

find_path(PostgreSQLInternal_INCLUDE_DIRS_postgres_fe_h
  NAMES postgres_fe.h
  PATH_SUFFIXES pgsql/server
  PATHS /usr/include/postgresql/12/server /usr/include/postgresql/13/server /usr/include/postgresql/14/server /usr/include/postgresql/15/server /usr/local/include/postgresql/server ${USERVER_PG_SERVER_INCLUDE_DIR}
)
list(APPEND PostgreSQLInternal_INCLUDE_DIRS ${PostgreSQLInternal_INCLUDE_DIRS_postgres_fe_h})
find_path(PostgreSQLInternal_INCLUDE_DIRS_libpq-int_h
  NAMES libpq-int.h
  PATH_SUFFIXES postgresql/internal pgsql/internal
  PATHS ${USERVER_PG_INCLUDE_DIR}/internal ${USERVER_PG_INCLUDE_DIR}/postgresql/internal /usr/local/include/postgresql/internal
)
list(APPEND PostgreSQLInternal_INCLUDE_DIRS ${PostgreSQLInternal_INCLUDE_DIRS_libpq-int_h})
find_path(PostgreSQLInternal_INCLUDE_DIRS_libpq-fe_h
  NAMES libpq-fe.h
  PATH_SUFFIXES postgresql pgsql
  PATHS ${USERVER_PG_INCLUDE_DIR} /usr/local/include
)
list(APPEND PostgreSQLInternal_INCLUDE_DIRS ${PostgreSQLInternal_INCLUDE_DIRS_libpq-fe_h})



if (PostgreSQLInternal_VERSION)
  set(PostgreSQLInternal_VERSION ${PostgreSQLInternal_VERSION})
endif()

if (NOT PostgreSQLInternal_VERSION)
  include(DetectVersion)

  if (UNIX AND NOT APPLE)
    deb_version(PostgreSQLInternal_VERSION libpq-dev)
    rpm_version(PostgreSQLInternal_VERSION postgresql-server-devel)
    
    pkg_version(PostgreSQLInternal_VERSION postgresql15-server)
  endif()
  if (APPLE)
    brew_version(PostgreSQLInternal_VERSION postgresql@14)
  endif()
  
endif()

 
find_package_handle_standard_args(
  PostgreSQLInternal
    REQUIRED_VARS
      PostgreSQLInternal_LIBRARIES
      PostgreSQLInternal_INCLUDE_DIRS
      
    FAIL_MESSAGE
      "${FULL_ERROR_MESSAGE}"
)
mark_as_advanced(
  PostgreSQLInternal_LIBRARIES
  PostgreSQLInternal_INCLUDE_DIRS
  
)

if (NOT PostgreSQLInternal_FOUND)
  if (PostgreSQLInternal_FIND_REQUIRED)
      message(FATAL_ERROR "${FULL_ERROR_MESSAGE}. Required version is at least ${PostgreSQLInternal_FIND_VERSION}")
  endif()

  return()
endif()

if (PostgreSQLInternal_FIND_VERSION)
  if (PostgreSQLInternal_VERSION VERSION_LESS PostgreSQLInternal_FIND_VERSION)
      message(STATUS
          "Version of PostgreSQLInternal is '${PostgreSQLInternal_VERSION}'. "
          "Required version is at least '${PostgreSQLInternal_FIND_VERSION}'. "
          "Ignoring found PostgreSQLInternal. "
          "Note: Set -DUSERVER_CHECK_PACKAGE_VERSIONS=0 to skip package version checks if the package is fine."
      )
      set(PostgreSQLInternal_FOUND OFF)
      return()
  endif()
endif()

 
if (NOT TARGET PostgreSQLInternal)
  add_library(PostgreSQLInternal INTERFACE IMPORTED GLOBAL)

  target_include_directories(PostgreSQLInternal INTERFACE ${PostgreSQLInternal_INCLUDE_DIRS})
  message(STATUS "PostgreSQLInternal include directories: ${PostgreSQLInternal_INCLUDE_DIRS}")
  target_link_libraries(PostgreSQLInternal INTERFACE ${PostgreSQLInternal_LIBRARIES})
  message(STATUS "PostgreSQLInternal libraries: ${PostgreSQLInternal_LIBRARIES}")
  
  # Target PostgreSQLInternal is created
endif()

if (PostgreSQLInternal_VERSION)
  set(PostgreSQLInternal_VERSION "${PostgreSQLInternal_VERSION}" CACHE STRING "Version of the PostgreSQLInternal")
endif()
