# AUTOGENERATED, DON'T CHANGE THIS FILE!


if (NOT USERVER_CHECK_PACKAGE_VERSIONS)
  unset(PythonDev_FIND_VERSION)
endif()

if (TARGET PythonDev)
  if (NOT PythonDev_FIND_VERSION)
      set(PythonDev_FOUND ON)
      return()
  endif()

  if (PythonDev_VERSION)
      if (PythonDev_FIND_VERSION VERSION_LESS_EQUAL PythonDev_VERSION)
          set(PythonDev_FOUND ON)
          return()
      else()
          message(FATAL_ERROR
              "Already using version ${PythonDev_VERSION} "
              "of PythonDev when version ${PythonDev_FIND_VERSION} "
              "was requested."
          )
      endif()
  endif()
endif()

set(FULL_ERROR_MESSAGE "Could not find `PythonDev` package.\n\tDebian: sudo apt update && sudo apt install python3-dev\n\tMacOS: brew install python3-dev\n\tFedora: sudo dnf install python3-dev\n\tArchLinux: sudo pacman -S python\\n")


include(FindPackageHandleStandardArgs)


find_path(PythonDev_INCLUDE_DIRS_Python_h
  NAMES Python.h
  PATHS /usr/include/python3m /usr/include/python3.6m /usr/include/python3.7m /usr/include/python3.8m /usr/include/python3.9m /usr/include/python3 /usr/include/python3.6 /usr/include/python3.7 /usr/include/python3.8 /usr/include/python3.9 /usr/include/python3.10 /usr/include/python3.11 /usr/include/python3.12 /usr/include/python3.13 /usr/include/python3.14
)
list(APPEND PythonDev_INCLUDE_DIRS ${PythonDev_INCLUDE_DIRS_Python_h})



if (PythonDev_VERSION)
  set(PythonDev_VERSION ${PythonDev_VERSION})
endif()

if (NOT PythonDev_VERSION)
  include(DetectVersion)

  if (UNIX AND NOT APPLE)
    deb_version(PythonDev_VERSION python3-dev)
    rpm_version(PythonDev_VERSION python3-dev)
    pacman_version(PythonDev_VERSION python)
    
  endif()
  if (APPLE)
    brew_version(PythonDev_VERSION python3-dev)
  endif()
  
endif()

 
find_package_handle_standard_args(
  PythonDev
    REQUIRED_VARS
      
      PythonDev_INCLUDE_DIRS
      
    FAIL_MESSAGE
      "${FULL_ERROR_MESSAGE}"
)
mark_as_advanced(
  
  PythonDev_INCLUDE_DIRS
  
)

if (NOT PythonDev_FOUND)
  if (PythonDev_FIND_REQUIRED)
      message(FATAL_ERROR "${FULL_ERROR_MESSAGE}. Required version is at least ${PythonDev_FIND_VERSION}")
  endif()

  return()
endif()

if (PythonDev_FIND_VERSION)
  if (PythonDev_VERSION VERSION_LESS PythonDev_FIND_VERSION)
      message(STATUS
          "Version of PythonDev is '${PythonDev_VERSION}'. "
          "Required version is at least '${PythonDev_FIND_VERSION}'. "
          "Ignoring found PythonDev. "
          "Note: Set -DUSERVER_CHECK_PACKAGE_VERSIONS=0 to skip package version checks if the package is fine."
      )
      set(PythonDev_FOUND OFF)
      return()
  endif()
endif()

 
if (NOT TARGET PythonDev)
  add_library(PythonDev INTERFACE IMPORTED GLOBAL)

  target_include_directories(PythonDev INTERFACE ${PythonDev_INCLUDE_DIRS})
  message(STATUS "PythonDev include directories: ${PythonDev_INCLUDE_DIRS}")
  
  # Target PythonDev is created
endif()

if (PythonDev_VERSION)
  set(PythonDev_VERSION "${PythonDev_VERSION}" CACHE STRING "Version of the PythonDev")
endif()
