# AUTOGENERATED, DON'T CHANGE THIS FILE!


if (NOT USERVER_CHECK_PACKAGE_VERSIONS)
  unset(clickhouse-cpp_FIND_VERSION)
endif()

if (TARGET clickhouse-cpp)
  if (NOT clickhouse-cpp_FIND_VERSION)
      set(clickhouse-cpp_FOUND ON)
      return()
  endif()

  if (clickhouse-cpp_VERSION)
      if (clickhouse-cpp_FIND_VERSION VERSION_LESS_EQUAL clickhouse-cpp_VERSION)
          set(clickhouse-cpp_FOUND ON)
          return()
      else()
          message(FATAL_ERROR
              "Already using version ${clickhouse-cpp_VERSION} "
              "of clickhouse-cpp when version ${clickhouse-cpp_FIND_VERSION} "
              "was requested."
          )
      endif()
  endif()
endif()

set(FULL_ERROR_MESSAGE "Could not find `clickhouse-cpp` package.\n\tDebian: sudo apt update && sudo apt install libyandex-clickhousecpp\n\tMacOS: brew install yandex-clickhouse-cpp\\n")


include(FindPackageHandleStandardArgs)

find_library(clickhouse-cpp_LIBRARIES_libclickhouse-cpp-lib_so_yandex-clickhousecpp
  NAMES libclickhouse-cpp-lib.so yandex-clickhousecpp
)
list(APPEND clickhouse-cpp_LIBRARIES ${clickhouse-cpp_LIBRARIES_libclickhouse-cpp-lib_so_yandex-clickhousecpp})

find_path(clickhouse-cpp_INCLUDE_DIRS_clickhouse_block_h
  NAMES clickhouse/block.h
  PATH_SUFFIXES yandex/clickhouse-cpp
)
list(APPEND clickhouse-cpp_INCLUDE_DIRS ${clickhouse-cpp_INCLUDE_DIRS_clickhouse_block_h})



if (clickhouse-cpp_VERSION)
  set(clickhouse-cpp_VERSION ${clickhouse-cpp_VERSION})
endif()

if (NOT clickhouse-cpp_VERSION)
  include(DetectVersion)

  if (UNIX AND NOT APPLE)
    deb_version(clickhouse-cpp_VERSION libyandex-clickhousecpp)
    
    
    
  endif()
  if (APPLE)
    brew_version(clickhouse-cpp_VERSION yandex-clickhouse-cpp)
  endif()
  
endif()

 
find_package_handle_standard_args(
  clickhouse-cpp
    REQUIRED_VARS
      clickhouse-cpp_LIBRARIES
      clickhouse-cpp_INCLUDE_DIRS
      
    FAIL_MESSAGE
      "${FULL_ERROR_MESSAGE}"
)
mark_as_advanced(
  clickhouse-cpp_LIBRARIES
  clickhouse-cpp_INCLUDE_DIRS
  
)

if (NOT clickhouse-cpp_FOUND)
  if (clickhouse-cpp_FIND_REQUIRED)
      message(FATAL_ERROR "${FULL_ERROR_MESSAGE}. Required version is at least ${clickhouse-cpp_FIND_VERSION}")
  endif()

  return()
endif()

if (clickhouse-cpp_FIND_VERSION)
  if (clickhouse-cpp_VERSION VERSION_LESS clickhouse-cpp_FIND_VERSION)
      message(STATUS
          "Version of clickhouse-cpp is '${clickhouse-cpp_VERSION}'. "
          "Required version is at least '${clickhouse-cpp_FIND_VERSION}'. "
          "Ignoring found clickhouse-cpp. "
          "Note: Set -DUSERVER_CHECK_PACKAGE_VERSIONS=0 to skip package version checks if the package is fine."
      )
      set(clickhouse-cpp_FOUND OFF)
      return()
  endif()
endif()

 
if (NOT TARGET clickhouse-cpp)
  add_library(clickhouse-cpp INTERFACE IMPORTED GLOBAL)

  target_include_directories(clickhouse-cpp INTERFACE ${clickhouse-cpp_INCLUDE_DIRS})
  message(STATUS "clickhouse-cpp include directories: ${clickhouse-cpp_INCLUDE_DIRS}")
  target_link_libraries(clickhouse-cpp INTERFACE ${clickhouse-cpp_LIBRARIES})
  message(STATUS "clickhouse-cpp libraries: ${clickhouse-cpp_LIBRARIES}")
  
  # Target clickhouse-cpp is created
endif()

if (clickhouse-cpp_VERSION)
  set(clickhouse-cpp_VERSION "${clickhouse-cpp_VERSION}" CACHE STRING "Version of the clickhouse-cpp")
endif()
