# AUTOGENERATED, DON'T CHANGE THIS FILE!

if (NOT PostgreSQL_FIND_VERSION OR PostgreSQL_FIND_VERSION VERSION_LESS 12)
    set(PostgreSQL_FIND_VERSION 12)
endif()

if (NOT USERVER_CHECK_PACKAGE_VERSIONS)
  unset(PostgreSQL_FIND_VERSION)
endif()

if (TARGET PostgreSQL)
  if (NOT PostgreSQL_FIND_VERSION)
      set(PostgreSQL_FOUND ON)
      return()
  endif()

  if (PostgreSQL_VERSION)
      if (PostgreSQL_FIND_VERSION VERSION_LESS_EQUAL PostgreSQL_VERSION)
          set(PostgreSQL_FOUND ON)
          return()
      else()
          message(FATAL_ERROR
              "Already using version ${PostgreSQL_VERSION} "
              "of PostgreSQL when version ${PostgreSQL_FIND_VERSION} "
              "was requested."
          )
      endif()
  endif()
endif()

set(FULL_ERROR_MESSAGE "Could not find `PostgreSQL` package.\n\tDebian: sudo apt update && sudo apt install libpq-dev\n\tMacOS: brew install postgresql@14\n\tFedora: sudo dnf install postgresql-static\n\tArchLinux: sudo pacman -S postgresql-libs\n\tFreeBSD: pkg install postgresql15-client\\n")


include(FindPackageHandleStandardArgs)

find_library(PostgreSQL_LIBRARIES_libpq_a
  NAMES libpq.a
  PATHS ${USERVER_PG_LIBRARY_DIR}
)
list(APPEND PostgreSQL_LIBRARIES ${PostgreSQL_LIBRARIES_libpq_a})

find_path(PostgreSQL_INCLUDE_DIRS_libpq-fe_h
  NAMES libpq-fe.h
  PATH_SUFFIXES postgresql pgsql
  PATHS ${USERVER_PG_INCLUDE_DIR} /usr/local/include
)
list(APPEND PostgreSQL_INCLUDE_DIRS ${PostgreSQL_INCLUDE_DIRS_libpq-fe_h})



if (PostgreSQL_VERSION)
  set(PostgreSQL_VERSION ${PostgreSQL_VERSION})
endif()

if (NOT PostgreSQL_VERSION)
  include(DetectVersion)

  if (UNIX AND NOT APPLE)
    deb_version(PostgreSQL_VERSION libpq-dev)
    rpm_version(PostgreSQL_VERSION postgresql-static)
    pacman_version(PostgreSQL_VERSION postgresql-libs)
    pkg_version(PostgreSQL_VERSION postgresql15-client)
  endif()
  if (APPLE)
    brew_version(PostgreSQL_VERSION postgresql@14)
  endif()
  
endif()

 
find_package_handle_standard_args(
  PostgreSQL
    REQUIRED_VARS
      PostgreSQL_LIBRARIES
      PostgreSQL_INCLUDE_DIRS
      
    FAIL_MESSAGE
      "${FULL_ERROR_MESSAGE}"
)
mark_as_advanced(
  PostgreSQL_LIBRARIES
  PostgreSQL_INCLUDE_DIRS
  
)

if (NOT PostgreSQL_FOUND)
  if (PostgreSQL_FIND_REQUIRED)
      message(FATAL_ERROR "${FULL_ERROR_MESSAGE}. Required version is at least ${PostgreSQL_FIND_VERSION}")
  endif()

  return()
endif()

if (PostgreSQL_FIND_VERSION)
  if (PostgreSQL_VERSION VERSION_LESS PostgreSQL_FIND_VERSION)
      message(STATUS
          "Version of PostgreSQL is '${PostgreSQL_VERSION}'. "
          "Required version is at least '${PostgreSQL_FIND_VERSION}'. "
          "Ignoring found PostgreSQL. "
          "Note: Set -DUSERVER_CHECK_PACKAGE_VERSIONS=0 to skip package version checks if the package is fine."
      )
      set(PostgreSQL_FOUND OFF)
      return()
  endif()
endif()

 
if (NOT TARGET PostgreSQL)
  add_library(PostgreSQL INTERFACE IMPORTED GLOBAL)

  target_include_directories(PostgreSQL INTERFACE ${PostgreSQL_INCLUDE_DIRS})
  message(STATUS "PostgreSQL include directories: ${PostgreSQL_INCLUDE_DIRS}")
  target_link_libraries(PostgreSQL INTERFACE ${PostgreSQL_LIBRARIES})
  message(STATUS "PostgreSQL libraries: ${PostgreSQL_LIBRARIES}")
  
  # Target PostgreSQL is created
endif()

if (PostgreSQL_VERSION)
  set(PostgreSQL_VERSION "${PostgreSQL_VERSION}" CACHE STRING "Version of the PostgreSQL")
endif()
