components_manager:
    coro_pool:
        initial_size: 500             # Preallocate 500 coroutines at startup.
        max_size: 1000                # Do not keep more than 1000 preallocated coroutines.

#############################################################################################################
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: 4         # Process tasks in 4 threads.
            thread_name: stegozavr-main  # OS will show the threads of this task processor with 'main-worker' prefix.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            thread_name: stegozavr-fs
            worker_threads: 30

    default_task_processor: main-task-processor
#############################################################################################################
    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: 8080            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: main-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: info
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dns-client:
            fs-task-processor: main-task-processor

        stegozavr_db:
            # postgresql connection string format: postgresql://username:password@dns:port/db-name
            dbconnection: 'postgresql://ortur:beoboba@localhost:5432/stegozavr_db'
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        tracer:                             # Component that helps to trace execution times and requests in logs.
            service-name: stegozavr         # "You know. You all know exactly who I am. Say my name. " (c)

        dynamic-config:                      # Dynamic config storage options, do nothing
            fs-cache-path: ''
        dynamic-config-fallbacks:            # Load options from file and push them into the dynamic config storage.
            fallback-path: dynamic_config_fallback.json

        testsuite-support: {}
#######################################################################################################################

        handler-decode:
            path: /v1/decode                       # Registering handler by URL '/decode'.
            method: GET                         # It will only reply to GET requests.
            task_processor: fs-task-processor   # Run it on File System bound task processor

        handler-encode:
            path: /v1/encode                       # Registering handler by URL '/encode'.
            method: GET                         # It will only reply to GET requests.
            task_processor: fs-task-processor   # Run it on File System task processor

        handler-register-user:
            path: /v1/register
            method: POST
            task_processor: main-task-processor

        handler-get-token:
            path: /v1/get_token
            method: GET
            task_processor: main-task-processor



